export { default as tribe_event_icon } from "./tribe_event_icon.svg";
export { default as event_tribe_location } from "./event_tribe_location.png";
export { default as hamburger_open_icon } from "./openHamburger.png";
export { default as facebook_icon } from "./logos_facebook.png";
export { default as instagram_icon } from "./skill-icons_instagram.png";
export { default as twitter_icon } from "./skill-icons_twitter.png";
export { default as hamburger_close_icon } from "./closeHamburger.png";
export { default as hero_left_panel } from './hero_left_panel.svg'
export { default as hero_right_panel } from './hero_right_panel.svg'
export { default as filter_icon } from './filter.svg'
export { default as who } from './who.svg'
export { default as trade_fair } from './trade_fair.svg'
export { default as wofbec } from './wofbec.svg'
export { default as halleluyah } from './halleluyah.svg'
export { default as charity_gala } from './charity_gala.svg'
export { default as techX } from './techX.svg'
export { default as dp1 } from './dp1.svg'
export { default as dp2 } from './dp2.svg'
export { default as dp3 } from './dp3.svg'
export { default as dp4 } from './dp4.svg'
export { default as event_creation } from './event__creation.svg'
export { default as attendee_registration } from './attendee_registration.svg'
export { default as attendee_management } from './attendee_management.svg'
export { default as event_promotion } from './event_promotion.svg'